LABELS_ADDRESS = "labels/"
IMAGES_ADDRESS = "images/"
HEADER_FILES_SUFFIX = ".hdr"
BUCHAR_FILES_SUFFIX = ".buchar"
IMAGE_FILES_SUFFIX = ".img"
OFFSETS_ADDRESS = 'meta/offsets.txt'
DECIMAL_POINT_ROUND = 2
POLARIZATION_THRESHOLD = 0.3

THRESHOLD_254 = 1.0
THRESHOLD_192 = 0.33
THRESHOLD_128 = -0.33
THRESHOLD_0 = -1.0
