__author__ = 'sharare'

TRAIN_ADDRESS = "TrainSetHW1/"
TEST_ADDRESS = "TestSetHW1/"
FILES_SUFFIX = ".txt"
NUMBER_OF_CHARACTERS_IN_A_LINE = 7
NUMBER_OF_LINES = 9
NUMBER_OF_TRAIN_IMAGES = 21
LABEL_SIZE = 7



